site_name: SDV NgX Widgets
site_description: SDV NgX Widgets est un pack de widgets pour angular5+ avec bootstrap
copyright: "&copy; SdV Plurimédia"
theme: readthedocs
site_dir: ./dist
use_directory_urls: false
extra_css:
  - css/extra.css
pages:
    - 'Accueil': 'index.md'
